export { default as HomePage } from './HomePage.vue';
export { default as LoaderPage } from './LoaderPage.vue';
export { default as LoginPage } from './LoginPage.vue';
export { default as InfoPage } from './InfoPage.vue';
export { default as RequestPage } from './RequestPage.vue';
export { default as RequestStatusPage } from './RequestStatusPage.vue';
export { default as ProfilePage } from './ProfilePage.vue';
export { default as NotFoundPage } from './NotFoundPage.vue';
export { default as ComingSoonPage } from './ComingSoonPage.vue';
